version: "3" # Compose.yml 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  docker-redis: # 서비스 명
    image: redis:5.0.8 # 사용할 이미지
    container_name: docker-redis-5.0.8 # 컨테이너 이름 설정
    ports:
      - "6379:6379" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    command: redis-server --appendonly yes
    volumes:
      - ~/docker/redis-5.0.8:/data # -v 옵션 ( 디렉토리 마운트 설정 )